services:
  twitter-persona-agents:
    container_name: twitter-persona-agents-app-prod
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8582:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - THREADS_ACCESS_TOKEN=${THREADS_ACCESS_TOKEN}
      - THREADS_USER_ID=${THREADS_USER_ID}
    env_file:
      - config/.env
    depends_on:
      - redis
    networks:
      - twitter-persona-agents-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: twitter-persona-agents-redis-prod
    volumes:
      - redis_data:/data
    networks:
      - twitter-persona-agents-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  twitter-persona-agents-network:
    driver: bridge