services:
  twitter-persona-agents:
    container_name: twitter-persona-agents-app
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8582:8000"
    volumes:
      - ../:/app
      - ../data:/app/data
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    env_file:
      - ../config/.env
    depends_on:
      - redis
    networks:
      - twitter-persona-agents-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - twitter-persona-agents-network

volumes:
  redis_data:

networks:
  twitter-persona-agents-network:
    driver: bridge